#############################################################################
# Makefile for building: projet
# Generated by qmake (2.01a) (Qt 4.7.0) on: Thu Apr 14 14:44:03 2011
# Project:  projet.pro
# Template: app
# Command: /opt/qtsdk-2010.05/qt/bin/qmake -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile projet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DPATH="\"/u/foleybov/Documents/IFT2905/Projet\"" -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2010.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2010.05/qt/include/QtCore -I/opt/qtsdk-2010.05/qt/include/QtGui -I/opt/qtsdk-2010.05/qt/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2010.05/qt/lib -lQtGui -L/opt/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = geoposition.cpp \
		geopositiondelegate.cpp \
		main.cpp \
		mainwindow.cpp \
		manote.cpp \
		note.cpp \
		notemodel.cpp \
		reservation.cpp \
		reservationmodel.cpp \
		simulateur.cpp \
		station.cpp \
		stationmodel.cpp \
		usager.cpp \
		usagermodel.cpp \
		vehicule.cpp \
		vehiculemodel.cpp \
		reservationproxymodel.cpp \
		robot.cpp \
		cartescene.cpp \
		carteelements.cpp \
		cartewidget.cpp \
		userinterface.cpp \
		page.cpp \
		mainmenupage.cpp moc_geopositiondelegate.cpp \
		moc_mainwindow.cpp \
		moc_note.cpp \
		moc_notemodel.cpp \
		moc_reservation.cpp \
		moc_reservationmodel.cpp \
		moc_simulateur.cpp \
		moc_station.cpp \
		moc_stationmodel.cpp \
		moc_usager.cpp \
		moc_usagermodel.cpp \
		moc_vehicule.cpp \
		moc_vehiculemodel.cpp \
		moc_robot.cpp \
		moc_reservationproxymodel.cpp \
		moc_cartescene.cpp \
		moc_carteelements.cpp \
		moc_cartewidget.cpp \
		moc_userinterface.cpp \
		moc_page.cpp \
		qrc_icones.cpp
OBJECTS       = geoposition.o \
		geopositiondelegate.o \
		main.o \
		mainwindow.o \
		manote.o \
		note.o \
		notemodel.o \
		reservation.o \
		reservationmodel.o \
		simulateur.o \
		station.o \
		stationmodel.o \
		usager.o \
		usagermodel.o \
		vehicule.o \
		vehiculemodel.o \
		reservationproxymodel.o \
		robot.o \
		cartescene.o \
		carteelements.o \
		cartewidget.o \
		userinterface.o \
		page.o \
		mainmenupage.o \
		moc_geopositiondelegate.o \
		moc_mainwindow.o \
		moc_note.o \
		moc_notemodel.o \
		moc_reservation.o \
		moc_reservationmodel.o \
		moc_simulateur.o \
		moc_station.o \
		moc_stationmodel.o \
		moc_usager.o \
		moc_usagermodel.o \
		moc_vehicule.o \
		moc_vehiculemodel.o \
		moc_robot.o \
		moc_reservationproxymodel.o \
		moc_cartescene.o \
		moc_carteelements.o \
		moc_cartewidget.o \
		moc_userinterface.o \
		moc_page.o \
		qrc_icones.o
DIST          = /opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		projet.pro
QMAKE_TARGET  = projet
DESTDIR       = 
TARGET        = projet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_cartewidget.h ui_userinterface.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: projet.pro  /opt/qtsdk-2010.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/opt/qtsdk-2010.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile projet.pro
/opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2010.05/qt/lib/libQtGui.prl:
/opt/qtsdk-2010.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile projet.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/projet1.0.0 || $(MKDIR) .tmp/projet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/projet1.0.0/ && $(COPY_FILE) --parents geoposition.h geopositiondelegate.h mainwindow.h manote.h note.h notemodel.h reservation.h reservationmodel.h simulateur.h station.h stationmodel.h usager.h usagermodel.h vehicule.h vehiculemodel.h robot.h reservationproxymodel.h cartescene.h carteelements.h cartewidget.h userinterface.h page.h mainmenupage.h .tmp/projet1.0.0/ && $(COPY_FILE) --parents icones.qrc .tmp/projet1.0.0/ && $(COPY_FILE) --parents geoposition.cpp geopositiondelegate.cpp main.cpp mainwindow.cpp manote.cpp note.cpp notemodel.cpp reservation.cpp reservationmodel.cpp simulateur.cpp station.cpp stationmodel.cpp usager.cpp usagermodel.cpp vehicule.cpp vehiculemodel.cpp reservationproxymodel.cpp robot.cpp cartescene.cpp carteelements.cpp cartewidget.cpp userinterface.cpp page.cpp mainmenupage.cpp .tmp/projet1.0.0/ && $(COPY_FILE) --parents mainwindow.ui cartewidget.ui userinterface.ui .tmp/projet1.0.0/ && (cd `dirname .tmp/projet1.0.0` && $(TAR) projet1.0.0.tar projet1.0.0 && $(COMPRESS) projet1.0.0.tar) && $(MOVE) `dirname .tmp/projet1.0.0`/projet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/projet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


tar:
	tar -zcf projet.tar.gz geoposition.cpp geopositiondelegate.cpp main.cpp mainwindow.cpp manote.cpp note.cpp notemodel.cpp reservation.cpp reservationmodel.cpp simulateur.cpp station.cpp stationmodel.cpp usager.cpp usagermodel.cpp vehicule.cpp vehiculemodel.cpp reservationproxymodel.cpp robot.cpp cartescene.cpp carteelements.cpp cartewidget.cpp userinterface.cpp page.cpp mainmenupage.cpp geoposition.h geopositiondelegate.h mainwindow.h manote.h note.h notemodel.h reservation.h reservationmodel.h simulateur.h station.h stationmodel.h usager.h usagermodel.h vehicule.h vehiculemodel.h robot.h reservationproxymodel.h cartescene.h carteelements.h cartewidget.h userinterface.h page.h mainmenupage.h mainwindow.ui cartewidget.ui userinterface.ui icones.qrc data/xml/map_montreal.osm data/xml/*.xml data/images/icons/*.png data/images/stations/*.jpg data/images/stations/*.gif data/images/vehicules/*.png projet.pro

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_geopositiondelegate.cpp moc_mainwindow.cpp moc_note.cpp moc_notemodel.cpp moc_reservation.cpp moc_reservationmodel.cpp moc_simulateur.cpp moc_station.cpp moc_stationmodel.cpp moc_usager.cpp moc_usagermodel.cpp moc_vehicule.cpp moc_vehiculemodel.cpp moc_robot.cpp moc_reservationproxymodel.cpp moc_cartescene.cpp moc_carteelements.cpp moc_cartewidget.cpp moc_userinterface.cpp moc_page.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_geopositiondelegate.cpp moc_mainwindow.cpp moc_note.cpp moc_notemodel.cpp moc_reservation.cpp moc_reservationmodel.cpp moc_simulateur.cpp moc_station.cpp moc_stationmodel.cpp moc_usager.cpp moc_usagermodel.cpp moc_vehicule.cpp moc_vehiculemodel.cpp moc_robot.cpp moc_reservationproxymodel.cpp moc_cartescene.cpp moc_carteelements.cpp moc_cartewidget.cpp moc_userinterface.cpp moc_page.cpp
moc_geopositiondelegate.cpp: geopositiondelegate.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) geopositiondelegate.h -o moc_geopositiondelegate.cpp

moc_mainwindow.cpp: mainwindow.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_note.cpp: note.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) note.h -o moc_note.cpp

moc_notemodel.cpp: note.h \
		notemodel.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) notemodel.h -o moc_notemodel.cpp

moc_reservation.cpp: reservation.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) reservation.h -o moc_reservation.cpp

moc_reservationmodel.cpp: reservation.h \
		reservationmodel.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) reservationmodel.h -o moc_reservationmodel.cpp

moc_simulateur.cpp: simulateur.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) simulateur.h -o moc_simulateur.cpp

moc_station.cpp: geoposition.h \
		station.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) station.h -o moc_station.cpp

moc_stationmodel.cpp: station.h \
		geoposition.h \
		stationmodel.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) stationmodel.h -o moc_stationmodel.cpp

moc_usager.cpp: geoposition.h \
		usager.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) usager.h -o moc_usager.cpp

moc_usagermodel.cpp: usager.h \
		geoposition.h \
		usagermodel.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) usagermodel.h -o moc_usagermodel.cpp

moc_vehicule.cpp: vehicule.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) vehicule.h -o moc_vehicule.cpp

moc_vehiculemodel.cpp: vehicule.h \
		vehiculemodel.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) vehiculemodel.h -o moc_vehiculemodel.cpp

moc_robot.cpp: robot.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) robot.h -o moc_robot.cpp

moc_reservationproxymodel.cpp: reservationmodel.h \
		reservation.h \
		reservationproxymodel.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) reservationproxymodel.h -o moc_reservationproxymodel.cpp

moc_cartescene.cpp: carteelements.h \
		geoposition.h \
		cartescene.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) cartescene.h -o moc_cartescene.cpp

moc_carteelements.cpp: carteelements.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) carteelements.h -o moc_carteelements.cpp

moc_cartewidget.cpp: geoposition.h \
		cartewidget.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) cartewidget.h -o moc_cartewidget.cpp

moc_userinterface.cpp: userinterface.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) userinterface.h -o moc_userinterface.cpp

moc_page.cpp: page.h
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) page.h -o moc_page.cpp

compiler_rcc_make_all: qrc_icones.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icones.cpp
qrc_icones.cpp: icones.qrc \
		data/images/icons/zoom_out.png \
		data/images/icons/home.png \
		data/images/icons/zoom_in.png
	/opt/qtsdk-2010.05/qt/bin/rcc -name icones icones.qrc -o qrc_icones.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_cartewidget.h ui_userinterface.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_cartewidget.h ui_userinterface.h
ui_mainwindow.h: mainwindow.ui
	/opt/qtsdk-2010.05/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_cartewidget.h: cartewidget.ui
	/opt/qtsdk-2010.05/qt/bin/uic cartewidget.ui -o ui_cartewidget.h

ui_userinterface.h: userinterface.ui
	/opt/qtsdk-2010.05/qt/bin/uic userinterface.ui -o ui_userinterface.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

geoposition.o: geoposition.cpp geoposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geoposition.o geoposition.cpp

geopositiondelegate.o: geopositiondelegate.cpp geoposition.h \
		geopositiondelegate.h \
		cartewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geopositiondelegate.o geopositiondelegate.cpp

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		stationmodel.h \
		station.h \
		geoposition.h \
		vehiculemodel.h \
		vehicule.h \
		reservationmodel.h \
		reservation.h \
		usagermodel.h \
		usager.h \
		notemodel.h \
		note.h \
		reservationproxymodel.h \
		manote.h \
		geopositiondelegate.h \
		simulateur.h \
		robot.h \
		cartewidget.h \
		cartescene.h \
		carteelements.h \
		userinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

manote.o: manote.cpp manote.h \
		note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manote.o manote.cpp

note.o: note.cpp note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o note.o note.cpp

notemodel.o: notemodel.cpp notemodel.h \
		note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notemodel.o notemodel.cpp

reservation.o: reservation.cpp reservation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reservation.o reservation.cpp

reservationmodel.o: reservationmodel.cpp reservationmodel.h \
		reservation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reservationmodel.o reservationmodel.cpp

simulateur.o: simulateur.cpp simulateur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulateur.o simulateur.cpp

station.o: station.cpp station.h \
		geoposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o station.o station.cpp

stationmodel.o: stationmodel.cpp stationmodel.h \
		station.h \
		geoposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stationmodel.o stationmodel.cpp

usager.o: usager.cpp usager.h \
		geoposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usager.o usager.cpp

usagermodel.o: usagermodel.cpp usagermodel.h \
		usager.h \
		geoposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usagermodel.o usagermodel.cpp

vehicule.o: vehicule.cpp vehicule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vehicule.o vehicule.cpp

vehiculemodel.o: vehiculemodel.cpp vehiculemodel.h \
		vehicule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vehiculemodel.o vehiculemodel.cpp

reservationproxymodel.o: reservationproxymodel.cpp reservationproxymodel.h \
		reservationmodel.h \
		reservation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reservationproxymodel.o reservationproxymodel.cpp

robot.o: robot.cpp robot.h \
		reservationmodel.h \
		reservation.h \
		usagermodel.h \
		usager.h \
		geoposition.h \
		stationmodel.h \
		station.h \
		notemodel.h \
		note.h \
		vehiculemodel.h \
		vehicule.h \
		reservationproxymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robot.o robot.cpp

cartescene.o: cartescene.cpp cartescene.h \
		carteelements.h \
		geoposition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cartescene.o cartescene.cpp

carteelements.o: carteelements.cpp carteelements.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carteelements.o carteelements.cpp

cartewidget.o: cartewidget.cpp cartescene.h \
		carteelements.h \
		geoposition.h \
		cartewidget.h \
		ui_cartewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cartewidget.o cartewidget.cpp

userinterface.o: userinterface.cpp userinterface.h \
		ui_userinterface.h \
		page.h \
		mainmenupage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o userinterface.o userinterface.cpp

page.o: page.cpp page.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o page.o page.cpp

mainmenupage.o: mainmenupage.cpp mainmenupage.h \
		page.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainmenupage.o mainmenupage.cpp

moc_geopositiondelegate.o: moc_geopositiondelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_geopositiondelegate.o moc_geopositiondelegate.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_note.o: moc_note.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_note.o moc_note.cpp

moc_notemodel.o: moc_notemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notemodel.o moc_notemodel.cpp

moc_reservation.o: moc_reservation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reservation.o moc_reservation.cpp

moc_reservationmodel.o: moc_reservationmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reservationmodel.o moc_reservationmodel.cpp

moc_simulateur.o: moc_simulateur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simulateur.o moc_simulateur.cpp

moc_station.o: moc_station.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_station.o moc_station.cpp

moc_stationmodel.o: moc_stationmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stationmodel.o moc_stationmodel.cpp

moc_usager.o: moc_usager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usager.o moc_usager.cpp

moc_usagermodel.o: moc_usagermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usagermodel.o moc_usagermodel.cpp

moc_vehicule.o: moc_vehicule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vehicule.o moc_vehicule.cpp

moc_vehiculemodel.o: moc_vehiculemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vehiculemodel.o moc_vehiculemodel.cpp

moc_robot.o: moc_robot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robot.o moc_robot.cpp

moc_reservationproxymodel.o: moc_reservationproxymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reservationproxymodel.o moc_reservationproxymodel.cpp

moc_cartescene.o: moc_cartescene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cartescene.o moc_cartescene.cpp

moc_carteelements.o: moc_carteelements.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_carteelements.o moc_carteelements.cpp

moc_cartewidget.o: moc_cartewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cartewidget.o moc_cartewidget.cpp

moc_userinterface.o: moc_userinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_userinterface.o moc_userinterface.cpp

moc_page.o: moc_page.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_page.o moc_page.cpp

qrc_icones.o: qrc_icones.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icones.o qrc_icones.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

